FROM openjdk:17-alpine
VOLUME /tmp
EXPOSE 8080

  # JAR 파일 위치 설정
ARG JAR_FILE=build/libs/backend-0.0.1-SNAPSHOT.jar

  # JAR 파일을 컨테이너로 복사
COPY ${JAR_FILE} app.jar

  # 앱 실행
ENTRYPOINT ["java", "-jar", "/app.jar"]
