# 1. 빌드 베이스 이미지 설정
FROM openjdk:17-jdk-slim AS builder

# 2. 작업 디렉토리 설정
WORKDIR /springboot-app

# 3. 필요한 파일들 복사
COPY . .

# 4. 실행 권한 부여
RUN chmod +x gradlew

# 5. 클린 빌드 및 JAR 파일 생성
RUN ./gradlew clean bootJar

# 6. 실제 실행을 위한 이미지 설정
FROM openjdk:17-jdk-slim

# 7. 작업 디렉토리 설정
WORKDIR /app

# 8. JAR 파일 복사
COPY --from=builder /springboot-app/build/libs/*.jar app.jar

# 9. application.properties 복사
COPY --from=builder /springboot-app/src/main/resources/application.properties /app/config/application.properties

# 10. 포트 설정
EXPOSE 8080

# 11. 애플리케이션 실행 (설정 파일 경로 명시)
ENTRYPOINT ["java", "-jar", "/app/app.jar", "--spring.config.location=file:/app/config/application.properties"]
